###依存句法分析服务端口号
server:
  port: 8801
###服务名称（服务注册到eureka中心）
spring:
  application:
    name: app-springcloud-dependencyParse
#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka/
  # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: true
   # 是否从其他的服务中心同步服务列表
    fetch-registry: true